[package]
name = "spacetime-module"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
spacetimedb = "1.8.0"
log = "0.4"
spacetime_engine = { path = "../../../dev/stdb/spacetime_engine" }
serde_json = "1.0.145"
serde = "1.0.228"
